### ISSUE TITLE
Use of 'integer'

### ISSUE THREAD

**Issue by jogu** [openid/OpenID4VCI#100]
Some fields are defined as 'Integer', e.g.:

> `c_nonce_expires_in`: OPTIONAL. Integer denoting the lifetime in seconds of the `c_nonce`.

I'm not sure what this really means (is it invalid to send `60.0`?) and what it's implications for interoperability/conformance testing are.

I'd suggest changing to 'number'.

**Comment by Sakurann** [comment]
is this somewhat related to issue #90?

**Comment by jogu** [comment]
(This one is trivial, it could probably be considered editorial. I might even do a PR for it...)
