### ISSUE TITLE
Multiple credentials of the same type

### ISSUE THREAD

**Issue by OIDF-automation** [openid/OpenID4VCI#11]
### Original Reporter: dwc8

Some issuers may issue multiple credentials of the same type. Examples include: two almost identical passports, once used by the holder to visit Israel and the other to visit Iran; or a current credit card that expires next month and a second one that starts the following month.

The current issuing API does not cater for this as the wallet can only specify the credential type and the issuer can only return a single credential. One solution would be to allow the issuer to return an array of credentials of the same type and format.

**Comment by Sakurann** [comment]
PR merged!
