### ISSUE TITLE
Credential Encryption Parameter Name Discrepancy

### ISSUE THREAD

**Issue by peppelinux** [openid/OpenID4VCI#113]
In the credential request we have the parameter names for the credential response encryption, defined in the text as follows:

- `credential_encryption_jwk`
- `credential_response_encryption_alg`
- `credential_response_encryption_enc`

`credential_encryption_jwk` does not include `response_` in it. Me and other implementers are wondering if this is intentional and why.

If this is not intentional, WDYT if we change the name to `credential_response_encryption_jwk`, for naming normalization? 

![immagine](https://github.com/openid/OpenID4VCI/assets/1297620/fdd277d1-f472-40bb-9fab-846a7db0b336)

**Comment by paulbastian** [comment]
Does it make sense to group them together into a separate JSON object?

**Comment by Sakurann** [comment]
I agree it is cleaner to rename to `credential_response_encryption_jwk` unless @awoie there was a reason why you chose to omit `_response` here? 
less sure about the grouping. it does not seem to be a convention in OAuth/OIDC, so we can probably leave as-is

**Comment by awoie** [comment]
> Does it make sense to group them together into a separate JSON object?

I used the same pattern that you can find here: https://openid.net/specs/openid-connect-discovery-1_0.html

**Comment by TakahikoKawasaki** [comment]
It appears that "request parameter names" are confused with "metadata names". Using a JSON object to encapsulate "request parameters" related to credential response encryption would not yield significant benefits. It would just make it a bit combersome for credential issuer implementations to accept the request parameters.

**Comment by paulbastian** [comment]
Proposal:
```
"credential_response_encryption" : {
    "jwk" : {},
    "alg" : "...",
    "enc" : "..."
}
```

**Comment by Sakurann** [comment]
@cobward is Spruce using these in production? Would you be ok with this breaking change? if so, I think we can try get this in before ID-1

**Comment by cobward** [comment]
We're fine with breaking changes at this point.
