### ISSUE TITLE
[has-PR] Define which object should be returned for `mdl_iso_cbor`

### ISSUE THREAD

**Issue by OIDF-automation** [openid/OpenID4VCI#12]
### Original Reporter: oterbu

ISO 18013-5 does not define a CDDL for mdoc or mdl. We should define which object we return in the `credential` response for `mdl_iso_cbor`. One candidate is the `Document` object from ISO 18013-5 8.3.2.1.2.2 but without `deviceSigned`. The ISO spec describes the CDDL for `Document`.

**Comment by Sakurann** [comment]
closing for the reason above. cc @awoie @cobward
