### ISSUE TITLE
Authorization Pending

### ISSUE THREAD

**Issue by cobward** [openid/OpenID4VCI#127]
Currently it is possible for the Authorization Server to await the completion of an asynchronous process before issuing an access token, using the `authorization_pending` error code. I have two questions:
1. Is there a reaons this is limited to the Pre-Authorized Code grant type?
2. What should the Authorization Server communicate to the client if this process results in an authentication error?

On a separate note, if we are using requirements from RFC8628 then we should make it explicit what those requirements are. Currently we say we are using `authorization_pending` and `slow_down` as defined in RFC8628 and then immediately redefined them, so I would suggest we just remove the reference entirely.

**Comment by paulbastian** [comment]
My understanding is that a number of people are in favour of dropping that feature all together and I agree.

**Comment by cobward** [comment]
@paulbastian I would have no objections to dropping the feature if we are replacing it with a better mechanism.

Without this feature is there any way for an issuer to use an authorization mechanism that requires asynchronous processing or approval? For example an issuer may want to include a human in the loop as part of a manual approval process.

**Comment by Sakurann** [comment]
@cobward your question is related to other open issues #31 and #60. would be great if we can consolidate discussion there.

@paulbastian, I think @tlodderstedt disagrees with entirely dropping an option to defer authorization. If `authorization_pending` has security concerns of a long-lived auth code, I think there is proposal on the table to keep getting a fresh auth code until it is ready to be exchanged to an Access Token, that we need to discuss

**Comment by cobward** [comment]
@Sakurann cheers for pointing them out Kristina. Should I raise a separate issue for this:
> On a separate note, if we are using requirements from RFC8628 then we should make it explicit what those requirements are. Currently we say we are using authorization_pending and slow_down as defined in RFC8628 and then immediately redefined them, so I would suggest we just remove the reference entirely.

**Comment by selfissued** [comment]
FYI, PR #180  changes this wording to the more accurate:
> This specification also uses the error codes `authorization_pending` and `slow_down` defined in [@!RFC8628] for the Pre-Authorized Code grant type:

**Comment by Sakurann** [comment]
>On a separate note, if we are using requirements from RFC8628 then we should make it explicit what those requirements are. Currently we say we are using authorization_pending and slow_down as defined in RFC8628 and then immediately redefined them, so I would suggest we just remove the reference entirely.

@cobward were your concerns addressed by the new text merged with Mike's PR?
