### ISSUE TITLE
DIF wallet rendering as an alternative option to the display attribute ?

### ISSUE THREAD

**Issue by ThierryThevenet** [openid/OpenID4VCI#129]
Would it be possible to propose to use https://identity.foundation/wallet-rendering/ as an alternative to the display attribute of the openid-configuration ?
The syntax allows more options.

**Comment by Sakurann** [comment]
last commit on that spec was on Apr 21, 2022, and it does not look maintained at all, which makes me very reluctant to add it as an alternative.
I would rather enhance the `display` part of VCI based on what is missing there now, potentially inspired by wallet rendering spec.

**Comment by ThierryThevenet** [comment]
Where can we find the syntax description of the display object ?

**Comment by Sakurann** [comment]
here: https://openid.github.io/OpenID4VCI/openid-4-verifiable-credential-issuance-wg-draft.html#section-10.2.3-2.11.2.6.1

**Comment by Sakurann** [comment]
@ThierryThevenet did you have a chance to take a look at `display` syntax in VCI to see if it meets your use-case and what is missing, if any?

**Comment by TimoGlastra** [comment]
One addition we have implemented in the DIIP interop profile in the Netherlands is the addition of the `background_image` for a credential.



This allows wallets to add a bit more personality to different credentials in the wallet and can make them easily recognizable. 

E.g. see example of some credentials issued by Sphereon to the Paradym Wallet. It's very similar to how cards are rendered in the Apple Wallet (see also example image attached)


![IMG_4833](https://github.com/openid/OpenID4VCI/assets/23165168/ef831130-7089-43b3-aa47-d9c73697d4c5)
![IMG_4832](https://github.com/openid/OpenID4VCI/assets/23165168/3fa364b5-3909-4410-aab9-7fb87af9696d)
![IMG_4834](https://github.com/openid/OpenID4VCI/assets/23165168/4b29834f-bfad-4eba-9cb6-411829445393)

cc @nklomp

**Comment by nklomp** [comment]
Please be aware that PE will probably move away from JSONPath, at least for the core, in favor of JSON Pointer.

**Comment by Sakurann** [comment]
@TimoGlastra @ThierryThevenet I think adding `background_image` makes sense.

If I understand correctly, the proposal is to add the display mapping object https://identity.foundation/wallet-rendering/#display-mapping-object to add text that the wallet can fallback to? Can you please elaborate why such fallback is needed? I am not sure issuer should be putting such, potentially sensitive/privacy revealing information, in the metadata...

**Comment by ThierryThevenet** [comment]
The most important feature of this object is the format, the path is easy to use. The fallback is sometimes needed as most of the db we use to issue credentials are incomplete.

**Comment by Sakurann** [comment]
ok, sounds like what you are asking for is to add a parameter for `value_dates`, correct? Something like was brought up in issue #90.

**Comment by nklomp** [comment]
Indeed having proper type support would greatly help in how wallets would render individual claims.

I should have some code lying around somewhere to start a library to take all kinds of methods to determine how to render claims. From JSON schema's (if present), to credential manifest, to media-type detection etc.

You could say that issuers should use schema's; but there are not about how to render values, and then there are also the different credential formats of course.
