### ISSUE TITLE
incorrect typ in proof type example

### ISSUE THREAD

**Issue by jogu** [openid/OpenID4VCI#134]
The example proof jwt in https://openid.github.io/OpenID4VCI/openid-4-verifiable-credential-issuance-wg-draft.html#section-7.2.1.1
 has "typ": "JWT" in the header, I think it should be "openid4vci-proof+jwt," as per https://openid.github.io/OpenID4VCI/openid-4-verifiable-credential-issuance-wg-draft.html#jwt-proof-type

**Comment by selfissued** [comment]
I agree.  I could add this fix to PR #144 if people want me to.

**Comment by Sakurann** [comment]
fixing this in #128
