### ISSUE TITLE
"A non-exhaustive list of valid values defined by this specification are" is weird language

### ISSUE THREAD

**Issue by jogu** [openid/OpenID4VCI#138]
The current draft contains phrases about "non-exhaustive list of valid values defined by this specification" in a few places:

>  non-exhaustive list of valid values defined by this specification are string, number, and image media types such as image/jpeg as defined in IANA media type registry for images 

(e.g. https://openid.github.io/OpenID4VCI/openid-4-verifiable-credential-issuance-wg-draft.html#appendix-E.2.2 )

> To express the specifics about the claim, the most deeply nested value MAY be an object that includes a following non-exhaustive list of parameters defined by this specification:

(e.g.  https://openid.github.io/OpenID4VCI/openid-4-verifiable-credential-issuance-wg-draft.html#appendix-E.1.1.2 )

In both cases I've not been able to find an exhaustive list of the values that the specification does actually define. I'm not sure exactly what is meant, in other parts of the specification language like "Below is a non-exhaustive list of valid parameters that MAY be included" is used which may be the intention, or perhaps it is more like "This specification defines the following parameters, other parameters may be used and implementations MUST ignore unrecognised parameters"?

**Comment by Sakurann** [comment]
in the first example, `string, number, and image media types such as image/jpeg as defined in IANA media type registry` is the non-exhaustive list.

in the second case, parameters that follow (mandatory, value_type, display) is the non-exhaustive list.

**Comment by jogu** [comment]
> in the first example, string, number, and image media types such as image/jpeg as defined in IANA media type registry is the non-exhaustive list.

Isn't that "an exhaustive list of the values defined by this specification"? Or are there more values defined elsewhere in VCI?

i.e. I read "A non-exhaustive list of valid values defined by this specification are" as "this is some of the values defined by this specification, there are also other values defined in other sections of this specification".

So if we look at:

> A non-exhaustive list of valid values defined by this specification are string, number, and image media types such as image/jpeg as defined in IANA media type registry for images"

I guess the intention is something like:

> Valid values are `string`, `number`, and image media types (for example, `image/jpeg`) as defined in IANA media type registry for images. Other values may also be used.

?

**Comment by selfissued** [comment]
I would drop the word "valid" from the phrases "valid values" and "valid parameters" since it doesn't add anything to the meaning.

I can add this change to PR #191 if people agree.

**Comment by Sakurann** [comment]
> I guess the intention is something like:
> 
>>Valid values are string, number, and image media types (for example, image/jpeg) as defined in IANA media type registry for images. Other values may also be used.

I think so. I think `non-exhaustive` was meant to express "Other values may also be used" and not "there are also other values defined in other sections of this specification".
