### ISSUE TITLE
Order should be an array of claims.keys

### ISSUE THREAD

**Issue by tlodderstedt** [openid/OpenID4VCI#146]
https://github.com/openid/oid4vc-haip-sd-jwt-vc/issues/81

**Comment by jogu** [comment]
I already noted this on https://github.com/openid/OpenID4VCI/pull/128 (though I can't seem to find the comment right now) and I believe Kristina already resolved it.

**Comment by jogu** [comment]
Yes, it's already resolved, the text in PR #128 now reads:

> * `order`: OPTIONAL. An array of the claim name values that lists them in the order they should be displayed by the Wallet.

I think we can close this issue.
