### ISSUE TITLE
Move Appendix E

### ISSUE THREAD

**Issue by paulbastian** [openid/OpenID4VCI#157]
Appendix E for the Credential Format Profiles is by far the most important annex, yet it is very far to the end in the document.
I've seen multiple developers wondering about credential format specific parameters, e.g. in Credential Request because they did not expect to scroll so far to the back.

Proposal: Move it to earlier Annex or move it into the main section.

**Comment by Sakurann** [comment]
I agree with moving it to Annex A.

**Comment by Sakurann** [comment]
think we can make this move before ID-1, after #128 is merged..
