### ISSUE TITLE
Replace mentions of PIN with new naming Transaction Code

### ISSUE THREAD

**Issue by cryptphil** [openid/OpenID4VCI#158]
The naming "PIN" was replaced with "Transaction Code" with PR #95 but there were still two locations where a PIN was mentioned.

In concrete, the PIN is still visible in the pre-authorized code flow figure in [Step 4](https://github.com/openid/OpenID4VCI/blob/main/openid-4-verifiable-credential-issuance-1_0.md?plain=1#L272) and in the [example](https://github.com/openid/OpenID4VCI/blob/main/examples/credential_offer_multiple_credentials.json#L13) for a credential offer for multiple credentials.

**Comment by Sakurann** [comment]
PR merged
