### ISSUE TITLE
Introduce concept of credential ID and shorten existing parameters

### ISSUE THREAD

**Issue by awoie** [openid/OpenID4VCI#160]
The spec should introduce the concept of credential identifiers in the terminology section, so it can be reused in other features, e.g., notification ID.

Then, we should shorten the `credential_identifiers` and `credential_identifier` to `credential_ids` and `credential_id`.

**Comment by awoie** [comment]
@danielfett ^^

**Comment by Sakurann** [comment]
I am not sure this is a good idea. there are multiple credential identifiers in the spec with very separate meaning. mainly:
- identifier in the credential offer that maps to the key in the credential issuer metadata map - credential configuration id
- identifier that can be used in the credential request to request different datasets of the same credential configuration.
- notification id

**Comment by Sakurann** [comment]
looking at this now, shortening credential_identifier to credential_id would make sense.

**Comment by jogu** [comment]
what would be the advantage of shortening things?

**Comment by Sakurann** [comment]
now that ID-1 review has started, I do not see why we should shorten the parameter name, which is a breaking change, without clear benefit..

the point of defining credential definition in the terminology has been covered in other issues - #91 I think? so could we close this issue?
