### ISSUE TITLE
Editorial Issues in Appendix E.2 and E.3

### ISSUE THREAD

**Issue by TakahikoKawasaki** [openid/OpenID4VCI#172]
Editorial issues found in the working group draft built on December 22, 2023, published at https://openid.github.io/OpenID4VCI/openid-4-verifiable-credential-issuance-wg-draft.html

### E.2.2. Credential Issuer Metadata, the example JSON

- The Japanese translations for `display[1].name` (在籍証明書) and `display[1].logo.alt_text` (大学のロゴ) are inappropriate. They mean "Certificate of Enrollment" and "Logo of University", respectively.

### E.3.2. Credential Issuer Metadata, the 1st paragraph

- `credentials_supported` -> `credential_configurations_supported`

### E.3.2. Credential Issuer Metadata, the example JSON

- `credentials_supported` -> `credential_configurations_supported`

### E.3.3. Authorization Details

- `vct` should not be required because `credential_configuration_id` is sufficient. (Like `doctype` is no longer required in the case of `mso_mdoc`.)
- The example JSON should contain `credential_configuration_id` and should not contain `format` and `vct`.

**Comment by TakahikoKawasaki** [comment]
### E.3.2. Credential Issuer Metadata, the example JSON

- It's better to change `last_name` to `family_name` to align with [5.1. Standard Claims](https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims) of OIDC Core 1.0.
- It might be worth considering to change `is_over_18`, `is_over_21`, `is_over_65` to `age_over_18`, `age_over_21`, `age_over_65`, respectively, to align with "7.2.5 Age attestation: nearest "true" attestation above request" of "[ISO/IEC 18013-5:2021](https://www.iso.org/standard/69084.html)".

### Others

There are two `proof_types_supported` in the draft. They should be changed to `proof_types`.

**Comment by selfissued** [comment]
Taka is of course right.  This especially matters in cultures like Korea, where the first name pronounced is the family name.  We should do this before the first Implementer's Draft.

**Comment by jogu** [comment]
I believe @selfissued fixed the two issues in E.3.2 (now moved to A.3.2 in the latest version of the spec).

https://github.com/openid/OpenID4VCI/pull/216 will fix the Japanese text.

The remaining issue to be resolved is the one in E.3.3 (now A.3.3):

> vct should not be required because credential_configuration_id is sufficient. (Like doctype is no longer required in the case of mso_mdoc.)

**Comment by Sakurann** [comment]
per discussion in #217, 

> vct should not be required because credential_configuration_id is sufficient. (Like doctype is no longer required in the case of mso_mdoc.)
> The example JSON should contain credential_configuration_id and should not contain format and vct.

is now valid, so i think we can close this issue.

**Comment by jogu** [comment]
I agree, any fix for #217 will fix the remaining issue Taka raised. We can just close now right?
