### ISSUE TITLE
OpenID4VCI: add authorization_details token response parameter

### ISSUE THREAD

**Issue by OIDF-automation** [openid/OpenID4VCI#2]
### Original Reporter: tlodderstedt

Section 7 of draft-ietf-oauth-rar requires: 

> In addition to the token response parameters as defined in \[RFC6749\], the authorization server MUST also return the authorization details as granted by the resource owner and assigned to the respective access token.

At least the example in Section 8.2 should therefore include the authorization\_details response parameter.

**Comment by Sakurann** [comment]
this is addressed by PR #65.
Does this mean that optional `authorization_details` parameter needs to be added to the token request too..?

**Comment by Sakurann** [comment]
PR merged
