### ISSUE TITLE
Add a section of Wallet invocation

### ISSUE THREAD

**Issue by paulbastian** [openid/OpenID4VCI#201]
OpenID4VP has a (small) section on how the Wallet shall be launched/invoked/started.
At least copying the section would not seem like a bad idea to me.

Especially section at https://openid.github.io/OpenID4VCI/openid-4-verifiable-credential-issuance-wg-draft.html#section-4.1-1
> The Credential Issuer sends Credential Offer using an HTTP GET request or an HTTP redirect to the Wallet's Credential Offer Endpoint defined in [Section 11.1](https://openid.github.io/OpenID4VCI/openid-4-verifiable-credential-issuance-wg-draft.html#client_metadata).

does not match what many wallets have implemented today. Rather referencing to a Wallet Invocation Section may be a better solution.

**Comment by peppelinux** [comment]
I agree, Wallet Invocation is something very particular in this field and it worth of a dedicated section (security considerations included I would add)

**Comment by Sakurann** [comment]
I agree. redirect and GET are definitely not the only options. I tried clarify this in PR #246. please review and comment if it meets your expectations.

**Comment by jogu** [comment]
Some or maybe all of this is probably resolved by the fix for #13, PR https://github.com/openid/OpenID4VCI/pull/380
