### ISSUE TITLE
Remove format from Credential Response

### ISSUE THREAD

**Issue by paulbastian** [openid/OpenID4VCI#204]
The format of the credential at this point is clear to both Issuer and Wallet. The parameter does not serve any purpose.

Proposal: delete it

**Comment by tlodderstedt** [comment]
the purpose of the format parameter is to clearly convey the format of the credential in the response, I'm not sure we should completely rely on the fact the format was specified in the credential request

**Comment by Sakurann** [comment]
when the issuer is offering 2 different formats in the same session, and the wallet is arbitrarily requesting issuance of those 2, having credential format explicitly in the response is helpful.

**Comment by paulbastian** [comment]
But the Wallet is sending the chosen `format` in the Credential Request though, so its 100% clear what the Issuer must send?

**Comment by awoie** [comment]
IMO, the issuer should respond with an `unsupported_credential_format`, right? In that case, I agree that the `format` might not be needed.
