### ISSUE TITLE
mention OAuth Server Metadata in Section 11.2.3.

### ISSUE THREAD

**Issue by tlodderstedt** [openid/OpenID4VCI#206]
The text currently refers to RFC 8414 but does not mention .well-known/oauth-authorization-server. Implementers typically seem to assume .well-known/openid-configuration shall be used for that purpose. I suggest adding a line mentioning .well-known/oauth-authorization-server.

**Comment by Sakurann** [comment]
Jan-11-2024 WG call - agreed this is editorial and worth doing.

**Comment by Sakurann** [comment]
PR merged
