### ISSUE TITLE
Examples of signed JWTs do not always have valid signatures

### ISSUE THREAD

**Issue by gffletch** [openid/OpenID4VCI#233]
Creating this issue here from the [bitbucket issue](https://bitbucket.org/openid/connect/issues/2053/signatures-in-jwt-examples-are-not-all) .

For those examples where the signature should validate we need to publish a public key so that developers can validate the example. If we don't want the signatures to be validateable, then we should make it clear that the signature is invalid. Maybe something like `.abd...`

**Comment by Sakurann** [comment]
Jan to go through the draft to see where the signatures need to be regenerated and where it needs ot be clarified that the signature is abbreviated.
