### ISSUE TITLE
cryptographic_binding_methods_supported value "mso" is used in mdl issuer metadata example but not defined in spec

### ISSUE THREAD

**Issue by jogu** [openid/OpenID4VCI#237]
https://github.com/openid/OpenID4VCI/blob/main/examples/credential_metadata_mso_mdoc.json uses `cryptographic_binding_methods_supported` value `mso` - however the VCI specification only defines the value `cose_key`:

> Support for keys expressed as a COSE Key object [[RFC8152](file:///Users/joseph/Downloads/openid-4-verifiable-credential-issuance-wg-draft.html#RFC8152)] (for example, used in [[ISO.18013-5](file:///Users/joseph/Downloads/openid-4-verifiable-credential-issuance-wg-draft.html#ISO.18013-5)]) is indicated by the value cose_key

**Comment by Sakurann** [comment]
good catch - will address in PR #235
