### ISSUE TITLE
cryptographic_binding_methods_supported text about supporting all DID methods is unclear

### ISSUE THREAD

**Issue by jogu** [openid/OpenID4VCI#239]
Spec currently sayings this when defined `cryptographic_binding_methods_supported`:

> Support for all DID methods listed in Section 13 of [@DID_Specification_Registries] is indicated by sending a DID without any method-name

I don't understand what 'sending a DID without any method-name' means. My guess would be:

> by sending the string `did:`.

However the DID Specification Registries is I think a living document, so as there is no reference to a particular dated version of the registry I think it is never clear what "all DID methods" means and hence I'd suggest just deleting this sentence entirely.

**Comment by Sakurann** [comment]
this is a very important clarification for the implementers who use DIDs.

> However the DID Specification Registries is I think a living document, so as there is no reference to a particular dated version of the registry I think it is never clear what "all DID methods" means

It basically means "all DID methods" in the registry at that point of time. will clarify

> I don't understand what 'sending a DID without any method-name' means. My guess would be:
> 
> > by sending the string did:.

what is meant is the same as in SIOP spec "Support for all DID methods listed in Section 13 of [[DID_Specification_Registries](https://openid.net/specs/openid-connect-self-issued-v2-1_0.html#DID_Specification_Registries)] is indicated by sending `did` without any method-name"  - will clarify.
