### ISSUE TITLE
Incomplete definition of `mandatory` in SD-JWT VC claim metadata

### ISSUE THREAD

**Issue by danielfett** [openid/OpenID4VCI#272]
The definition of the `mandatory` key in the claim display metadata in the format profiles in Appendix A seems to be incomplete for SD-JWT VC.

The first two read:

> `mandatory`: OPTIONAL. Boolean which, when set to `true`, indicates that the Credential Issuer will always include this claim in the issued Credential. If set to `false`, the claim is not included in the issued Credential if the wallet did not request the inclusion of the claim, and/or if the Credential Issuer chose to not include the claim. If the `mandatory` parameter is omitted, the default value is `false`.

The one for SD-JWT VC reads:

> `mandatory`: OPTIONAL. Boolean which when set to `true` indicates the claim MUST be present in the issued Credential. If the `mandatory` property is omitted its default should be assumed to be `false`.

Additional question: Why is there a normative keyword in the latter but not the previous two?

This is the PR introducing this change, but I don't have the time for archeology right now: https://github.com/openid/OpenID4VCI/pull/128

**Comment by Sakurann** [comment]
when we introduced sd-jwt vc profile we used the text which was the same as the rest of the credential formats - that one is the original one. however, at the same time, in the prep for ID-1, we updated to the text to the upper one in your issue. that one is most recent, so need to upgrade sd-jwt vc one to that one.

**Comment by danielfett** [comment]
Thanks for the clarification! Can you please check whether the definition that I used in this PR is up-to date?

https://github.com/openid/OpenID4VCI/pull/276/files#diff-1f424614b35a9899813079f1b1f6218631a2aedd993368ccb89bb81a9eda0289R2229-R2253
