### ISSUE TITLE
Batch Credential Response, description correction and improvement

### ISSUE THREAD

**Issue by babisRoutis** [openid/OpenID4VCI#273]
The protocol provides the following description:

> The following parameters are used in the Batch Credential Response:
> 
> credential_responses: REQUIRED. Array that contains Credential Response objects, 
> as defined in (#credential-request), and/or Deferred Credential Response objects, as defined in (#deferred-credential-request). 
> Every entry of the array corresponds to the Credential Request object at the same array 
> index in the credential_requests parameter of the Batch Credential Request.
> c_nonce: OPTIONAL. The c_nonce as defined in (#credential-response).
> c_nonce_expires_in: OPTIONAL. The c_nonce_expires_in as defined in (#credential-response).
> 

I think there are two issues

- [ ] In the definition of `credential_responses` two links are being provided pointing to `credential-request` and `deferred-credential-request`. This is not correct though because the text describes credential responses (not requests)
- [ ] The description of `credential_responses` is perhaps not absolutely correct. Reading it literally one could  think that each member of the `credential_responses` array should be exactly like either a credential or deferred response. I think though that's not the case because those responses contain also `c_nonce` & `c_nonce_expires_in`  whereas batch response considers them (correctly) top-level attributes.

**Comment by Sakurann** [comment]
thank you for spotting this. I think your observation is correct and we need a PR to fix this
