### ISSUE TITLE
tx_code describes both the descriptor and the value

### ISSUE THREAD

**Issue by paulbastian** [openid/OpenID4VCI#301]
I got Implementer feedback twice, that it is confusing, that `tx_code` is the parameter value for both:
- the descriptor of the Transaction Code in the Credential Offer including the formatting, length and description
- the value of the Transaction Code in the Token Request

It seemed to confuse people that parameter names are the same.

Possible solution could be to rename the object in the Credential Offer to `tx_code_description`.

**Comment by Sakurann** [comment]
I really don't think the breaking change of renaming the parameter in the Offer is worth it. 
Let's just add a note that parameter in the credential offer is a description.
