### ISSUE TITLE
IETF SD-JWT VC > Credential Response missing example (A.3.5)

### ISSUE THREAD

**Issue by timcappalli** [openid/OpenID4VCI#327]
Section [A.3.5 Credential Response](https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0.html#name-credential-response-6) is missing a non-normative example for the SW-JWT VC response.

<img width="770" alt="image" src="https://github.com/openid/OpenID4VCI/assets/6476604/993764cf-bb7b-4b6c-a262-02dd2f021c42">

**Comment by Sakurann** [comment]
that's because response is a base64url encoded sd-jwt vc exactly as defined here: https://drafts.oauth.net/oauth-sd-jwt-vc/draft-ietf-oauth-sd-jwt-vc.html#section-3.3-25
but guess we can do a PR pointing to a section in sd-jwt vc spec.
