### ISSUE TITLE
Previously defined parameter `credentials` is used in the example in 4.1.2.

### ISSUE THREAD

**Issue by moratori** [openid/OpenID4VCI#348]
I checked the [Editors' Draft](https://openid.github.io/OpenID4VCI/openid-4-verifiable-credential-issuance-wg-draft.html#name-sending-credential-offer-by) version. The example in 4.1.2 uses a parameter called `credentials`.
I believe that using `credential_configuration_ids` is appropriate for the current latest specification.

Current example:
(Percent encoding is decoded for readability.)
```
GET /credential_offer?credential_offer={"credential_issuer":"https://credential-issuer.example.com","credentials":["UniversityDegree_JWT","org.iso.18013.5.1.mDL"],"grants":{"urn:ietf:params:oauth:grant-type:pre-authorized_code":{"pre-authorized_code":"oaKazRN8I0IbtZ0C7JuMn5","tx_code":{}}}}
```

**Comment by Sakurann** [comment]
@deshmukhrajvardhan to make a change:

change credentials parameter to credential_configuration_ids in this section: https://openid.github.io/OpenID4VCI/openid-4-verifiable-credential-issuance-wg-draft.html#section-4.1.2
