### ISSUE TITLE
Might need to clarify better how authz req parameters are included in PAR

### ISSUE THREAD

**Issue by Sakurann** [openid/OpenID4VCI#361]
got asked if they are top-level.
including example might help

**Comment by bc-pi** [comment]
https://www.rfc-editor.org/rfc/rfc9126.html#section-2.1 seems relevant

**Comment by jogu** [comment]
Was it signed or unsigned PAR requests they were confused about / we should include an example for?

**Comment by jogu** [comment]
Marking as pending close given we have an example, but it's not clear to me what people were confused about.

**Comment by jogu** [comment]
closing as per above comment - if there's anything that's unclear in the latest revision of the spec please let us know the details.
