### ISSUE TITLE
Redundant note in token response (section 6.2)

### ISSUE THREAD

**Issue by lalc** [openid/OpenID4VCI#362]
Spec reference: https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0.html#section-6.2

In the successful token response scenario, if you use `scope` in the authorization request (5.1.2 scenario), the token response will not contain the authorization details or the credential identifiers.

In this scenario, the note "Credential Instance identifier(s) cannot be used when the scope parameter is used in the Authorization Request to request issuance of a Credential" is misleading and unnecessary. Perhaps it should be mentioned only in the credential request chapter.

**Comment by Sakurann** [comment]
I understand that it might sound redundant, but we actually added this note, because implementer asked for this clarification, and I am inclined to keep it..?

cc @paulbastian

**Comment by paulbastian** [comment]
I would favour to keep it, the fact that scopes and authorisation_details are different flows seems not obvious to newcomers, at the same time credential_identifiers is a particular feature that enables certain things that scopes are not able to do.

**Comment by jogu** [comment]
no objections so closing as per Kristina's previous comment.
