### ISSUE TITLE
change sd-jwt vc type identifier from `vc+sd-jwt` to `dc+sd-jwt`

### ISSUE THREAD

**Issue by Sakurann** [openid/OpenID4VCI#414]
per changes here: https://github.com/oauth-wg/oauth-sd-jwt-vc/pull/268

**Comment by timcappalli** [comment]
FWIW, this would align well with the rest of the ecosystem where OID4VCI and OID4VP plays, so I'm all for it.

**Comment by selfissued** [comment]
Agreed on the change

**Comment by charsleysa** [comment]
@Sakurann this can be closed as the PR has been merged

**Comment by jogu** [comment]
Ah thanks! Closing. For future reference if you put "closes #XXX" in the PR description the issue will autoclose when it's merged.
