### ISSUE TITLE
polymorphic claims in VCI metadata

### ISSUE THREAD

**Issue by Sakurann** [openid/OpenID4VCI#422]
Open badge v3 credentials are used extensively throughout the education sector in the US. OBV3 supports an "identity" object that contains variable data. For example
```json
{
  "identityHash": "jane@example.com",
  "identityType": "email"
}
```
but the same structure can also hold a name
```json
{
  "identityHash": "Jane Foobar",
  "identityType": "name"
}
```

Something like the below would support it, but it requires conditional logic
```json
[{
  "path": ["identifier", "identityHash"],
  "display": [{
    "name": "Name",
    "path": ["identifier", "identityType"],
    "condition": "= 'name'"
  }, {
    "name": "Email",
    "path": ["identifier", "identityType"],
    "condition": "= 'emailAddress'"
  }]
}]
```
where condition must require `[< <= = != > >=] <literal>`.
It benefit being that it can be combined with the locales

_Originally posted by @sloops77 in https://github.com/openid/OpenID4VCI/pull/276#discussion_r1591672432_

**Comment by sloops77** [comment]
@Sakurann thanks for creating this

**Comment by sloops77** [comment]
I'll retiterate that the need for this comes primarily from a single, but popular, credential format 1Edtech's Open Badge (formally Mozilla's) which has been ported to VCDM for its v3

**Comment by sloops77** [comment]
@Sakurann I have communicated with 1edtech guys and they are ok with this not being supported as the intention of these polymorphic claims is not to be used for display purposes. They are also amenable to updating the next version of open badge to remove these polymorphic claims. 

As the creator of this issue, iI think we would all be happier if this issue were closed

**Comment by Sakurann** [comment]
thank you so much, @sloops77
