### ISSUE TITLE
Fix 'note to editors' in dynamic credential request section

### ISSUE THREAD

**Issue by jogu** [openid/OpenID4VCI#434]
https://openid.github.io/OpenID4VCI/openid-4-verifiable-credential-issuance-wg-draft.html#name-dynamic-credential-request contains:

> Note to the editors: We need to sort out the Credential Issuer's client_id with the Wallet and potentially add an example with wallet_issuer and user_hint.

We should fix/remove this.

**Comment by Sakurann** [comment]
i think this is a duplicate or should be tacked as part of https://github.com/openid/OpenID4VCI/issues/145

**Comment by Sakurann** [comment]
closing in a week unless this is not a duplicate

**Comment by jogu** [comment]
yeah, that works, thank you! I tried to search but didn't manage to find that issue quickly
