### ISSUE TITLE
[ID2] Merge Deferred Credential Endpoint into a Credential Endpoint

### ISSUE THREAD

**Issue by OIDF-automation** [openid/OpenID4VCI#6]
### Original Reporter: KristinaYasuda

Simplify deferred issuance by using credential endpoint to do a deferred issuance instead of a separate endpoint called deferred credential endpoint. for example, right now, two separate endpoints need to manage status of `acceptance_token`.

When the Wallet wants deferred issuance, it will send acceptance token to the credential endpoint using the same access token it initially used to obtain acceptance\_token.

‌

**Comment by Sakurann** [comment]
closing it as someone who opened it as I think there is no implementation experience pointing towards merging.
