### ISSUE TITLE
Add option for credential offer initated Authorization Code to Section 3

### ISSUE THREAD

**Issue by paulbastian** [openid/OpenID4VCI#76]
The Authorization Code Flow has the option to start wallet-initiated by the Authorization Request and the option to start issuer-initiated with a credential offer. The latter option is missing in the high-level description in Section 3.4. I propose to add this option to the sequence diagram and in the text as option.

**Comment by peppelinux** [comment]
In my view the flow may consider these elements

- we cannot think that every kind of wallet solution may implement a fully working discovery UI for all the VCI of one or more networks/federations
- requirement: even if a wallet solution may offer an embedded discovery UI for the well known VCI within a common context like a nation or a well known network (as it would be R&S) there are cases where the user decides to reach a known vci though the www for asking a credential issuance

the flow would be

- the user open the we browser and navigates to the vci web page, selecting the credential he/she wants to obtain
- the vci web page provides a qrcode (or a url/formpost if the flow is same-device) where the parameters for requesting an auth code flow are provided
- the user frames the qrcode (or open the wallet app according to the universal-link/url-scheme provided in the same-device flow) then the request to the authotization endpoint of the VCI starts

**Comment by RosaliaGaleano** [comment]
I agree with the proposal. I highlight that the same cross-device flow described by @peppelinux , should also be guaranteed on same-device (without the QR Code)

**Comment by paulbastian** [comment]
I think that this is covered already by the spec here: https://openid.bitbucket.io/connect/openid-4-verifiable-credential-issuance-1_0.html#section-4.1.1-4.1.1
But its just not very obvious and needs more emphasize. I will try to make a PR.

**Comment by Sakurann** [comment]
the point of section 3 is not to exhaustively illustrate all the possible variations of the flow. Having said that there are only three possible combinations of how to initiate the flow and the grant type and two of them are already covered in the spec: 

1. pre-auth code flow with credential offer -> section 3.5
2. authz code flow without credential offer -> section 3.4
3. authz code flow with credential offer

provided option 3 can be expressed in a concise manner, I agree adding it to the spec could add more clarity and be benefiial!
