### ISSUE TITLE
Credential/Callback Endpoints lacking the information about the user session

### ISSUE THREAD

**Issue by Sakurann** [openid/OpenID4VCI#79]
there is an `issuer_state` parameter that can be passed in the Credential Offer to be used in the authorization code flow that the wallet is required to include in the authorization request when received.

It's functionality is somewhat similar to that of pre_authorization code. Torsten reminded me that the original use-case to add this parameter was: " if the user logs in prior to receiving a credential offer, when receiving issuer_state, the AS can offer an SSO experience while ensuring it is the same user. In cross device session, issuer_state can also be used to allow the AS to force login with the same identity.

In our implementation, there is also a need for the Credential Issuer to know the original session of the user because the issuer maybe issuing multiple credentials of the same type to different users and the Issuer need to know the original user session. Suggested way forward is to ask the wallet to pass the issuer_state in the credential request (in addition to the authorization request), when isser_state was received  in the credential offer. Feedback appreciated!

**Comment by tlodderstedt** [comment]
Passing the issuer_state and an access token (which was issued based on the data in issuer_state) create raise conditions. The issuer_state might not match what was passed on the authorization request. 
In my opinion, if the issuer needs to know data from the issuer_state, the AS should put them into the access token.

**Comment by peppelinux** [comment]
@tlodderstedt It makes sense, however the current specs doesn't require the access token in JWT format

**Comment by jogu** [comment]
> It makes sense, however the current specs doesn't require the access token in JWT format

I presume Torsten meant either by value (e.g. JWT format) or by reference (e.g. accessible via token introspection).

I tend to agree with Torsten - if the Credential Issuer needs details that were passed originally to the authorization server then these should be made available (we don't need to say how) to the credential issuer by the authorization server - in the same way (in traditional OAuth) the AS has to convey to the RS what scopes were granted, for what user, etc.

Asking the wallet to pass issuer_state again raises all kinds of difficult questions (and potential security holes) about what should happen if the issuer_state passed to the credential issuer differs to the one passed to the authorization server.

**Comment by Sakurann** [comment]
Let me take a step back because I think me using the term `issuer_state` and jumping to a suggested solution caused confusion. 

The problem we face is Credential Endpoint lacking the information about the user session that led to the generation of a Credential Offer. For example, when multiple credentials are being issued to the same user account but on different devices/browsers; or when copies of same credential (same type/format/schema) are being issued to the different user accounts. The information to differentiate these is opaque to the AS and cannot go into the Access token. It's close to a state generated by the service/RS that is opaque to the AS.

so the idea might be closer to something like a new `user_session` top-level claim in the credential offer that is agnostic to the grant type that is passed back to the Credential Endpoint as opposed to reusing the current `authorization_code.issuer_state` credential offer parameter.

**Comment by jogu** [comment]
> The problem we face is Credential Endpoint lacking the information about the user session that led to the generation of a Credential Offer. For example, when multiple credentials are being issued to the same user account but on different devices/browsers; or when copies of same credential (same type/format/schema) are being issued to the different user accounts. The information to differentiate these is opaque to the AS and cannot go into the Access token. It's close to a state generated by the service/RS that is opaque to the AS.

I'm not sure these values can be opaque to the AS - if they're opaque to the AS how does the AS obtain user consent for the particular credential to be issued to this wallet?

I don't see how we can get away from the access token being used for the user session binding. If we rely on the client to tell the RS what credential needs to be issued then we open up the possibility for an attacker to ask for a credential that wasn't the one the user authorised the release of to this session?

**Comment by Sakurann** [comment]
> if they're opaque to the AS how does the AS obtain user consent for the particular credential to be issued to this wallet?

using scopes. AS knows what consent to by looking at the scope value.

**Comment by Sakurann** [comment]
the information that would go into into `user_session` is only about the browser session of the user, so that when the issuer finishes the issuance (sending credential response and optionally receiving a callback), it knows which browser session to update.

there could be multiple credentials of the same format/type being issued at the same time or same user having multiple issuance sessions for different credentials (on different devices or something), etc. 

We are extending AS in production to be used in VCI authorization code flow, and there is no possibility to add additional parameters in the Access Tokens that AS already mints. 
and besides it feels dangerous putting an information received from the wallet in the authorization_request (like current issuer_state) into the Access Token. and it also feels wrong to put a browser session into the Access Token

**Comment by Sakurann** [comment]
Discussed at IIW with @tlodderstedt @jogu @decentralgabe and others. I renamed the issue, because in the course of discussions, it boiled down to the Callback Endpoint being able to receive information about the user session that resulted in the Credential Offer, so that the Issuer backend can communicate that to its frontend after receiving a callback.

Current proposal would be to define a new parameter `callback_session` (placeholder name) in the Credential Offer, that the Wallet must pass in the callback alognside callback_ids. I can modify PR #70 accordingly if this sounds ok.

**Comment by Sakurann** [comment]
we talked internally with our engineers and for audit/logging purposes (e.g. to be able to know tie the sessions and the credential issuance), credential endpoint receiving `callback_session` in the credential request is important in addition to callback endpoint.

(apologies for changing the issuer title back end forth... this one is the final I believe)

**Comment by Sakurann** [comment]
once the issue is described, there seem to be an agreement that passing a parameter like `callback_handle` from credential offer to credential request/callback request is the direction. there seems to be, however, a varying degree of agreement whether this mechanism should be in the specification or not. The biggest concern seems to be that allowing in the spec to pass along something like `callback_handle` in the Credential request/Callback Request will lead to developers doing all sorts of scary things, including using `callback_handle` instead of DPoP proof or Access Token… (based on folks’ experience with what developers put in OAuth `state`parameter already… but there are also opinions that it is not a concern..

**Comment by danielfett** [comment]
For the record, I share these concerns and would vote for not describing this option in the spec.

**Comment by tlodderstedt** [comment]
I second Daniel's concerns (even though I initially leant towards adding this feature).

**Comment by Sakurann** [comment]
closing for now as does not seem to be consensus to introduce this feature in the main spec.

Microsoft's implementation introduces this parameter, so maybe we can revisit this topic based on the implementation experience.

**Comment by TimoGlastra** [comment]
Has there been any discussion or progress since on this topic? Curious to hear about implementation experience as well. In trying to implement the authorization code flow for issuance in a generic / spec compliant way I found it is impossible (?) to correlate the offer session back to the issued access token when the wallet retrieves the credential on the credential request endpoint.

I know there's `issuer_state`, but this requires oid4vci specific modifications to the authorization server. Would that be the recommended approach, putting `issuer_state` in the access token?

**Comment by muisit** [comment]
Forgive my ignorance, but regarding this whole issue: would it not be easier to remove the requirement to have the wallet pass the issuer_state to the AS and instead require the wallet to reflect it back, like browsers do with cookies, to the issuer? In that way, you will not create the artificial race condition based on a value that the AS cannot evaluate or process anyway and has no meaning in the context of Authorization? The AS is not going to change anything in its authorization process based on the content of the issuer state value.

We _do_ need the issuer state or session_ref or callback_handle or callback_session in order for the issuer front-end to smoothly guide the user in the whole process of credential issuance. The current protocol does not accomodate for a slew of additional 'headers' to be passed like is done for HTTP, so there is no way to properly maintain session in a cross-device flow.
I do not think the OAuth session_ref will be usefull, by the way, because it refers to the session at the AS side. We need the session on the RP side.

Finally, opting to _not_ describe such an option in the specification and instead relying on parties to implement their own solution is severely hampering interop between different wallets and issuers. I do not understand why one would suggest this, but this is probably my lack of insight. I would value to learn the argument.
