### ISSUE TITLE
more examples how scopes are used

### ISSUE THREAD

**Issue by Sakurann** [openid/OpenID4VCI#81]
> I think we only have this one example using scopes now - it would be great to have examples for the other options too (so 3 in total I think? one with scope, one with authorization_details, one with identifiers)

_Originally posted by @jogu in https://github.com/openid/OpenID4VCI/pull/65#discussion_r1326056827_

**Comment by Sakurann** [comment]
@jogu can you please elaborate a bit more where you would like to see more examples using scopes? I looked through the spec and it was not obviously to me.

**Comment by jogu** [comment]
I honestly don't know anymore. I had a look through the current spec and I can't see any options that don't have a corresponding authorization request example. I think we can just close this issue.
