### ISSUE TITLE
Uniform usage of "JSON String" vs. "String" (/Object/Array/...)

### ISSUE THREAD

**Issue by danielfett** [openid/OpenID4VCI#97]
When describing the types of JSON-encoded parameters, the wording is not uniform right now.

IMO, wordings such as the following should be avoided to ensure that the spec is clear:

> credentials: REQUIRED. A JSON array, where every entry is a JSON object or a JSON string.

Instead, the following wording is fine:

> credentials: REQUIRED. An array, where every entry is an object or a string.

(Assuming that it is clear that the object where `credentials` is part of is JSON encoded.)

When we repeat "JSON" in the description of an already JSON-encoded object, it is redundant and can be misleading (the string itself is not JSON-encoded before being put into the data structure).

**Comment by Sakurann** [comment]
agreed that `String` is sufficient, given there might be few instances where that clarification is needed - DanielF will assess :)
